//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webVeterinaria.svUser {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Users", Namespace="http://schemas.datacontract.org/2004/07/wcfVeterinaria")]
    [System.SerializableAttribute()]
    public partial class Users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CELULARField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CONTRASEÑAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CORREOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ESTADOUSUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDUSUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBRECOMPLETOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TIPOUSUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USUARIOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CELULAR {
            get {
                return this.CELULARField;
            }
            set {
                if ((object.ReferenceEquals(this.CELULARField, value) != true)) {
                    this.CELULARField = value;
                    this.RaisePropertyChanged("CELULAR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CONTRASEÑA {
            get {
                return this.CONTRASEÑAField;
            }
            set {
                if ((object.ReferenceEquals(this.CONTRASEÑAField, value) != true)) {
                    this.CONTRASEÑAField = value;
                    this.RaisePropertyChanged("CONTRASEÑA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CORREO {
            get {
                return this.CORREOField;
            }
            set {
                if ((object.ReferenceEquals(this.CORREOField, value) != true)) {
                    this.CORREOField = value;
                    this.RaisePropertyChanged("CORREO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESTADO {
            get {
                return this.ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADOField, value) != true)) {
                    this.ESTADOField = value;
                    this.RaisePropertyChanged("ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ESTADOUSUARIO {
            get {
                return this.ESTADOUSUARIOField;
            }
            set {
                if ((this.ESTADOUSUARIOField.Equals(value) != true)) {
                    this.ESTADOUSUARIOField = value;
                    this.RaisePropertyChanged("ESTADOUSUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDUSUARIO {
            get {
                return this.IDUSUARIOField;
            }
            set {
                if ((this.IDUSUARIOField.Equals(value) != true)) {
                    this.IDUSUARIOField = value;
                    this.RaisePropertyChanged("IDUSUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRECOMPLETO {
            get {
                return this.NOMBRECOMPLETOField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBRECOMPLETOField, value) != true)) {
                    this.NOMBRECOMPLETOField = value;
                    this.RaisePropertyChanged("NOMBRECOMPLETO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPO {
            get {
                return this.TIPOField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPOField, value) != true)) {
                    this.TIPOField = value;
                    this.RaisePropertyChanged("TIPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TIPOUSU {
            get {
                return this.TIPOUSUField;
            }
            set {
                if ((this.TIPOUSUField.Equals(value) != true)) {
                    this.TIPOUSUField = value;
                    this.RaisePropertyChanged("TIPOUSU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USUARIO {
            get {
                return this.USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.USUARIOField, value) != true)) {
                    this.USUARIOField = value;
                    this.RaisePropertyChanged("USUARIO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tipoUsu", Namespace="http://schemas.datacontract.org/2004/07/wcfVeterinaria")]
    [System.SerializableAttribute()]
    public partial class tipoUsu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDTIPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPOUSUField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDTIPO {
            get {
                return this.IDTIPOField;
            }
            set {
                if ((this.IDTIPOField.Equals(value) != true)) {
                    this.IDTIPOField = value;
                    this.RaisePropertyChanged("IDTIPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPOUSU {
            get {
                return this.TIPOUSUField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPOUSUField, value) != true)) {
                    this.TIPOUSUField = value;
                    this.RaisePropertyChanged("TIPOUSU");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="estadoUsu", Namespace="http://schemas.datacontract.org/2004/07/wcfVeterinaria")]
    [System.SerializableAttribute()]
    public partial class estadoUsu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDESTADOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESTADO {
            get {
                return this.ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADOField, value) != true)) {
                    this.ESTADOField = value;
                    this.RaisePropertyChanged("ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDESTADO {
            get {
                return this.IDESTADOField;
            }
            set {
                if ((this.IDESTADOField.Equals(value) != true)) {
                    this.IDESTADOField = value;
                    this.RaisePropertyChanged("IDESTADO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="svUser.IserviceUsers")]
    public interface IserviceUsers {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceUsers/AgregarUsuario", ReplyAction="http://tempuri.org/IserviceUsers/AgregarUsuarioResponse")]
        string AgregarUsuario(webVeterinaria.svUser.Users usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceUsers/AgregarUsuario", ReplyAction="http://tempuri.org/IserviceUsers/AgregarUsuarioResponse")]
        System.Threading.Tasks.Task<string> AgregarUsuarioAsync(webVeterinaria.svUser.Users usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceUsers/EliminarUsario", ReplyAction="http://tempuri.org/IserviceUsers/EliminarUsarioResponse")]
        string EliminarUsario(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceUsers/EliminarUsario", ReplyAction="http://tempuri.org/IserviceUsers/EliminarUsarioResponse")]
        System.Threading.Tasks.Task<string> EliminarUsarioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceUsers/ActualizarUsuario", ReplyAction="http://tempuri.org/IserviceUsers/ActualizarUsuarioResponse")]
        string ActualizarUsuario(webVeterinaria.svUser.Users usuario, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceUsers/ActualizarUsuario", ReplyAction="http://tempuri.org/IserviceUsers/ActualizarUsuarioResponse")]
        System.Threading.Tasks.Task<string> ActualizarUsuarioAsync(webVeterinaria.svUser.Users usuario, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceUsers/validarLogin", ReplyAction="http://tempuri.org/IserviceUsers/validarLoginResponse")]
        webVeterinaria.svUser.Users validarLogin(string usuario, string contra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceUsers/validarLogin", ReplyAction="http://tempuri.org/IserviceUsers/validarLoginResponse")]
        System.Threading.Tasks.Task<webVeterinaria.svUser.Users> validarLoginAsync(string usuario, string contra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceUsers/BuscarUsuario", ReplyAction="http://tempuri.org/IserviceUsers/BuscarUsuarioResponse")]
        webVeterinaria.svUser.Users BuscarUsuario(int idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceUsers/BuscarUsuario", ReplyAction="http://tempuri.org/IserviceUsers/BuscarUsuarioResponse")]
        System.Threading.Tasks.Task<webVeterinaria.svUser.Users> BuscarUsuarioAsync(int idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceUsers/listarTipo", ReplyAction="http://tempuri.org/IserviceUsers/listarTipoResponse")]
        webVeterinaria.svUser.tipoUsu[] listarTipo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceUsers/listarTipo", ReplyAction="http://tempuri.org/IserviceUsers/listarTipoResponse")]
        System.Threading.Tasks.Task<webVeterinaria.svUser.tipoUsu[]> listarTipoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceUsers/listarEstado", ReplyAction="http://tempuri.org/IserviceUsers/listarEstadoResponse")]
        webVeterinaria.svUser.estadoUsu[] listarEstado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceUsers/listarEstado", ReplyAction="http://tempuri.org/IserviceUsers/listarEstadoResponse")]
        System.Threading.Tasks.Task<webVeterinaria.svUser.estadoUsu[]> listarEstadoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IserviceUsersChannel : webVeterinaria.svUser.IserviceUsers, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IserviceUsersClient : System.ServiceModel.ClientBase<webVeterinaria.svUser.IserviceUsers>, webVeterinaria.svUser.IserviceUsers {
        
        public IserviceUsersClient() {
        }
        
        public IserviceUsersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IserviceUsersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IserviceUsersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IserviceUsersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AgregarUsuario(webVeterinaria.svUser.Users usuario) {
            return base.Channel.AgregarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<string> AgregarUsuarioAsync(webVeterinaria.svUser.Users usuario) {
            return base.Channel.AgregarUsuarioAsync(usuario);
        }
        
        public string EliminarUsario(int id) {
            return base.Channel.EliminarUsario(id);
        }
        
        public System.Threading.Tasks.Task<string> EliminarUsarioAsync(int id) {
            return base.Channel.EliminarUsarioAsync(id);
        }
        
        public string ActualizarUsuario(webVeterinaria.svUser.Users usuario, int id) {
            return base.Channel.ActualizarUsuario(usuario, id);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarUsuarioAsync(webVeterinaria.svUser.Users usuario, int id) {
            return base.Channel.ActualizarUsuarioAsync(usuario, id);
        }
        
        public webVeterinaria.svUser.Users validarLogin(string usuario, string contra) {
            return base.Channel.validarLogin(usuario, contra);
        }
        
        public System.Threading.Tasks.Task<webVeterinaria.svUser.Users> validarLoginAsync(string usuario, string contra) {
            return base.Channel.validarLoginAsync(usuario, contra);
        }
        
        public webVeterinaria.svUser.Users BuscarUsuario(int idusuario) {
            return base.Channel.BuscarUsuario(idusuario);
        }
        
        public System.Threading.Tasks.Task<webVeterinaria.svUser.Users> BuscarUsuarioAsync(int idusuario) {
            return base.Channel.BuscarUsuarioAsync(idusuario);
        }
        
        public webVeterinaria.svUser.tipoUsu[] listarTipo() {
            return base.Channel.listarTipo();
        }
        
        public System.Threading.Tasks.Task<webVeterinaria.svUser.tipoUsu[]> listarTipoAsync() {
            return base.Channel.listarTipoAsync();
        }
        
        public webVeterinaria.svUser.estadoUsu[] listarEstado() {
            return base.Channel.listarEstado();
        }
        
        public System.Threading.Tasks.Task<webVeterinaria.svUser.estadoUsu[]> listarEstadoAsync() {
            return base.Channel.listarEstadoAsync();
        }
    }
}
