//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webVeterinaria.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsAlmacen", Namespace="http://schemas.datacontract.org/2004/07/wcfVeterinaria")]
    [System.SerializableAttribute()]
    public partial class clsAlmacen : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDITEMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PRECIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRESENTACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int STOCKField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ESTADO {
            get {
                return this.ESTADOField;
            }
            set {
                if ((this.ESTADOField.Equals(value) != true)) {
                    this.ESTADOField = value;
                    this.RaisePropertyChanged("ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDITEM {
            get {
                return this.IDITEMField;
            }
            set {
                if ((this.IDITEMField.Equals(value) != true)) {
                    this.IDITEMField = value;
                    this.RaisePropertyChanged("IDITEM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE {
            get {
                return this.NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREField, value) != true)) {
                    this.NOMBREField = value;
                    this.RaisePropertyChanged("NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PRECIO {
            get {
                return this.PRECIOField;
            }
            set {
                if ((this.PRECIOField.Equals(value) != true)) {
                    this.PRECIOField = value;
                    this.RaisePropertyChanged("PRECIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRESENTACION {
            get {
                return this.PRESENTACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.PRESENTACIONField, value) != true)) {
                    this.PRESENTACIONField = value;
                    this.RaisePropertyChanged("PRESENTACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int STOCK {
            get {
                return this.STOCKField;
            }
            set {
                if ((this.STOCKField.Equals(value) != true)) {
                    this.STOCKField = value;
                    this.RaisePropertyChanged("STOCK");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServicioAlmacen")]
    public interface IServicioAlmacen {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlmacen/AgregarAlmacen", ReplyAction="http://tempuri.org/IServicioAlmacen/AgregarAlmacenResponse")]
        string AgregarAlmacen(webVeterinaria.ServiceReference1.clsAlmacen almacen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlmacen/AgregarAlmacen", ReplyAction="http://tempuri.org/IServicioAlmacen/AgregarAlmacenResponse")]
        System.Threading.Tasks.Task<string> AgregarAlmacenAsync(webVeterinaria.ServiceReference1.clsAlmacen almacen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlmacen/ElimnarAlmacen", ReplyAction="http://tempuri.org/IServicioAlmacen/ElimnarAlmacenResponse")]
        bool ElimnarAlmacen(webVeterinaria.ServiceReference1.clsAlmacen almacen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlmacen/ElimnarAlmacen", ReplyAction="http://tempuri.org/IServicioAlmacen/ElimnarAlmacenResponse")]
        System.Threading.Tasks.Task<bool> ElimnarAlmacenAsync(webVeterinaria.ServiceReference1.clsAlmacen almacen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlmacen/ActualizarAlmacen", ReplyAction="http://tempuri.org/IServicioAlmacen/ActualizarAlmacenResponse")]
        string ActualizarAlmacen(webVeterinaria.ServiceReference1.clsAlmacen almacen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlmacen/ActualizarAlmacen", ReplyAction="http://tempuri.org/IServicioAlmacen/ActualizarAlmacenResponse")]
        System.Threading.Tasks.Task<string> ActualizarAlmacenAsync(webVeterinaria.ServiceReference1.clsAlmacen almacen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlmacen/ObtenerAlmacen", ReplyAction="http://tempuri.org/IServicioAlmacen/ObtenerAlmacenResponse")]
        System.Data.DataSet ObtenerAlmacen();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlmacen/ObtenerAlmacen", ReplyAction="http://tempuri.org/IServicioAlmacen/ObtenerAlmacenResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerAlmacenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlmacen/FetchUpdatedRecords", ReplyAction="http://tempuri.org/IServicioAlmacen/FetchUpdatedRecordsResponse")]
        System.Data.DataSet FetchUpdatedRecords(webVeterinaria.ServiceReference1.clsAlmacen almacen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlmacen/FetchUpdatedRecords", ReplyAction="http://tempuri.org/IServicioAlmacen/FetchUpdatedRecordsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FetchUpdatedRecordsAsync(webVeterinaria.ServiceReference1.clsAlmacen almacen);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioAlmacenChannel : webVeterinaria.ServiceReference1.IServicioAlmacen, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioAlmacenClient : System.ServiceModel.ClientBase<webVeterinaria.ServiceReference1.IServicioAlmacen>, webVeterinaria.ServiceReference1.IServicioAlmacen {
        
        public ServicioAlmacenClient() {
        }
        
        public ServicioAlmacenClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioAlmacenClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAlmacenClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAlmacenClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AgregarAlmacen(webVeterinaria.ServiceReference1.clsAlmacen almacen) {
            return base.Channel.AgregarAlmacen(almacen);
        }
        
        public System.Threading.Tasks.Task<string> AgregarAlmacenAsync(webVeterinaria.ServiceReference1.clsAlmacen almacen) {
            return base.Channel.AgregarAlmacenAsync(almacen);
        }
        
        public bool ElimnarAlmacen(webVeterinaria.ServiceReference1.clsAlmacen almacen) {
            return base.Channel.ElimnarAlmacen(almacen);
        }
        
        public System.Threading.Tasks.Task<bool> ElimnarAlmacenAsync(webVeterinaria.ServiceReference1.clsAlmacen almacen) {
            return base.Channel.ElimnarAlmacenAsync(almacen);
        }
        
        public string ActualizarAlmacen(webVeterinaria.ServiceReference1.clsAlmacen almacen) {
            return base.Channel.ActualizarAlmacen(almacen);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarAlmacenAsync(webVeterinaria.ServiceReference1.clsAlmacen almacen) {
            return base.Channel.ActualizarAlmacenAsync(almacen);
        }
        
        public System.Data.DataSet ObtenerAlmacen() {
            return base.Channel.ObtenerAlmacen();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerAlmacenAsync() {
            return base.Channel.ObtenerAlmacenAsync();
        }
        
        public System.Data.DataSet FetchUpdatedRecords(webVeterinaria.ServiceReference1.clsAlmacen almacen) {
            return base.Channel.FetchUpdatedRecords(almacen);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FetchUpdatedRecordsAsync(webVeterinaria.ServiceReference1.clsAlmacen almacen) {
            return base.Channel.FetchUpdatedRecordsAsync(almacen);
        }
    }
}
